name: Data
on:
  schedule:
    - cron: "5 8 * * *"
jobs:
  gemfa_export:
    name: GemFA export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm ci
      - run: npm run data:download
      - run: npm run data:convert
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update GemFA export
          branch: update-gemfa-export
          title: Update GemFA export
